

## # Aula 5

- [Testes Unitários](#testes-unitários)
- [`assert`](#assert)
- [`pytest`](#pytest)
- [Testando Strings](#testando-strings)
- [Organizando Testes em Pastas](#organizando-testes-em-pastas)
- [Conclusão](#conclusão)

## Testes Unitários

- Até agora, é provável que você tenha testado seu próprio código usando instruções `print`.
- Alternativamente, você pode ter contado com o CS50 para testar seu código por você!
- Na indústria, é mais comum escrever código para testar seus próprios programas.
- Na janela do console, digite `code calculator.py`. Observe que você pode ter codificado este arquivo anteriormente em uma palestra anterior. No editor de texto, verifique se seu código aparece como segue:

      def main():
          x = int(input("Qual é o valor de x? "))
          print("x ao quadrado é", square(x))


      def square(n):
          return n * n


      if __name__ == "__main__":
          main()

  Observe que você poderia testar o código acima usando alguns números óbvios, como `2`. No entanto, considere por que você pode querer criar um teste que garanta que o código acima funcione corretamente.

- Seguindo a convenção, vamos criar um novo programa de teste digitando `code test_calculator.py` e modifique seu código no editor de texto da seguinte forma:

      from calculator import square


      def main():
          test_square()


      def test_square():
          if square(2) != 4:
              print("2 ao quadrado não é 4")
          if square(3) != 9:
              print("3 ao quadrado não é 9")


      if __name__ == "__main__":
          main()

  Observe que estamos importando a função `square` de `square.py` na primeira linha de código. Por convenção, estamos criando uma função chamada `test_square`. Dentro dessa função, definimos algumas condições para testar.

- Na janela do console, digite `python test_calculator.py`. Você observará que nada está sendo exibido. Pode ser que tudo esteja funcionando bem! Alternativamente, pode ser que nossa função de teste não tenha descoberto um dos "casos extremos" que pode produzir um erro.
- No momento, nosso código testa duas condições. Se quisermos testar muitas mais condições, nosso código de teste pode facilmente se tornar inchado. Como poderíamos expandir nossas capacidades de teste sem expandir nosso código de teste?

## `assert`

- O comando `assert` do Python nos permite dizer ao compilador que algo, alguma afirmação, é verdadeira. Podemos aplicar isso ao nosso código de teste da seguinte forma:

      from calculator import square


      def main():
          test_square()


      def test_square():
          assert square(2) == 4
          assert square(3) == 9


      if __name__ == "__main__":
          main()

  Perceba que estamos afirmando definitivamente o que `square(2)` e `square(3)` devem ser iguais. Nosso código foi reduzido de quatro linhas de teste para duas.

- Podemos intencionalmente quebrar nosso código de calculadora modificando-o da seguinte forma:

      def main():
          x = int(input("Qual é o valor de x? "))
          print("O quadrado de x é", square(x))


      def square(n):
          return n + n


      if __name__ == "__main__":
          main()

  Note que alteramos o operador `*` para `+` na função `square`.

- Agora, ao executar `python test_square.py` no console, você perceberá que um `AssertionError` é gerado pelo compilador. Essencialmente, isso significa que uma de nossas condições não foi atendida.
- Um dos desafios que estamos enfrentando agora é que nosso código pode se tornar ainda mais pesado se quisermos fornecer uma saída de erro mais descritiva para nossos usuários. É possível codificar da seguinte maneira:

      from calculator import square


      def main():
          test_square()


      def test_square():
          try:
              assert square(2) == 4
          except AssertionError:
              print("O quadrado de 2 não é 4")
          try:
              assert square(3) == 9
          except AssertionError:
              print("O quadrado de 3 não é 9")
          try:
              assert square(-2) == 4
          except AssertionError:
              print("O quadrado de -2 não é 4")
          try:
              assert square(-3) == 9
          except AssertionError:
              print("O quadrado de -3 não é 9")
          try:
              assert square(0) == 0
          except AssertionError:
              print("O quadrado de 0 não é 0")


      if __name__ == "__main__":
          main()

  Note que a execução desse código irá produzir vários erros. No entanto, não está produzindo todos os erros mencionados acima. Isso ilustra que vale a pena testar vários casos para capturar situações onde há erros de codificação.

- O código acima ilustra um grande desafio: como tornar mais fácil testar o código sem dezenas de linhas de código como o exemplo acima?

Você pode aprender mais na documentação do Python sobre o [`assert`](https://docs.python.org/3/reference/simple_stmts.html#assert).

## `pytest`

- `pytest` é uma biblioteca de terceiros que permite testar unitariamente seu programa. Isso significa que você pode testar suas funções dentro do programa.
- Para utilizar o `pytest`, digite `pip install pytest` no seu terminal.
- Antes de aplicar o `pytest` ao nosso próprio programa, modifique sua função `test_calculator` da seguinte maneira:

      from calculator import square


      def test_assert():
          assert square(2) == 4
          assert square(3) == 9
          assert square(-2) == 4
          assert square(-3) == 9
          assert square(0) == 0

  Observe como o código acima verifica todas as condições que queremos testar.

- O `pytest` nos permite executar nosso programa diretamente através dele, de modo que possamos visualizar mais facilmente os resultados de nossas condições de teste.
- Na janela do terminal, digite `pytest test_calculator.py`. Você irá notar imediatamente que a saída será fornecida. Observe o `F` vermelho próximo ao topo da saída, indicando que algo em seu código falhou. Além disso, observe que o `E` vermelho fornece algumas dicas sobre os erros em seu programa `calculator.py`. Com base na saída, podemos imaginar um cenário em que `3 * 3` retornou `6` em vez de `9`. Com base nos resultados deste teste, podemos corrigir nosso código `calculator.py` da seguinte maneira:

      def main():
          x = int(input("Qual é o valor de x? "))
          print("O quadrado de x é", square(x))


      def square(n):
          return n * n


      if __name__ == "__main__":
          main()

  Observe que alteramos o operador `+` para `*` na função `square`, retornando-a para um estado funcional.

- Ao executar novamente o comando `pytest test_calculator.py`, observe como nenhum erro é produzido. Parabéns!
- No momento, não é ideal que o `pytest` pare de executar após o primeiro teste falhado. Novamente, vamos retornar nosso código `calculator.py` para seu estado quebrado:

      def main():
          x = int(input("Qual é o valor de x? "))
          print("O quadrado de x é", square(x))


      def square(n):
          return n + n


      if __name__ == "__main__":
          main()

  Observe que alteramos o operador `*` para `+` na função `square`, retornando-a para um estado quebrado.

- Para melhorar nosso código de teste, vamos modificar o arquivo `test_calculator.py` para dividir o código em diferentes grupos de testes:

      from calculator import square


      def test_positive():
          assert square(2) == 4
          assert square(3) == 9


      def test_negative():
          assert square(-2) == 4
          assert square(-3) == 9


      def test_zero():
          assert square(0) == 0

  Observe que dividimos os mesmos cinco testes em três funções diferentes. Frameworks de teste como o `pytest` executarão cada função, mesmo que haja uma falha em uma delas. Ao executar novamente o comando `pytest test_calculator.py`, você perceberá que muitos mais erros estão sendo exibidos. A saída de erro adicional permite explorar mais a fundo o que pode estar causando problemas em seu código.

- Após melhorar nosso código de teste, retorne seu código `calculator.py` ao estado total de funcionamento:

      def main():
          x = int(input("Qual é o valor de x? "))
          print("O quadrado de x é", square(x))


      def square(n):
          return n * n


      if __name__ == "__main__":
          main()

  Observe que alteramos o operador `+` para `*` na função `square`, retornando-a para um estado funcional.

- Ao executar novamente o comando `pytest test_calculator.py`, você perceberá que nenhum erro é encontrado.
- Em resumo, cabe a você, como programador, definir quantas condições de teste achar necessário!

Você pode aprender mais na documentação do Pytest em [`pytest`](https://docs.pytest.org/en/7.1.x/getting-started.html).

## Testando Strings

- Voltando no tempo, considere o código a seguir `hello.py`:

      def main():
          name = input("Qual é o seu nome? ")
          hello(name)


      def hello(to="mundo"):
          print("olá,", to)


      if __name__ == "__main__":
          main()

  Observe que podemos querer testar o resultado da função `hello`.

- Considere o seguinte código para `test_hello.py`:

      from hello import hello


      def test_hello():
          assert hello("David") == "olá, David"
          assert hello() == "olá, mundo"

  Ao analisar este código, você acha que esta abordagem de teste funcionará bem? Por que este teste pode não funcionar bem? Observe que a função `hello` em `hello.py` imprime algo: Isto é, ela não retorna um valor!

- Podemos alterar nossa função `hello` dentro de `hello.py` da seguinte forma:

      def main():
          name = input("Qual é o seu nome? ")
          print(hello(name))


      def hello(to="mundo"):
          return f"olá, {to}"


      if __name__ == "__main__":
          main()

  Observe que alteramos nossa função `hello` para retornar uma string. Isso significa efetivamente que agora podemos usar `pytest` para testar a função `hello`.

- Executando `pytest test_hello.py`, nosso código passará em todos os testes!
- Assim como nosso caso de teste anterior nesta lição, podemos dividir nossos testes separadamente:

      from hello import hello


      def test_default():
          assert hello() == "olá, mundo"


      def test_argument():
          assert hello("David") == "olá, David"

  Observe que o código acima separa nosso teste em várias funções para que todas elas sejam executadas, mesmo se ocorrer um erro.

## Organizando Testes em Pastas

- O código de teste de unidade usando vários testes é tão comum que você tem a capacidade de executar uma pasta inteira de testes com um único comando.
- Primeiro, na janela do terminal, execute `mkdir test` para criar uma pasta chamada `test`.
- Em seguida, para criar um teste dentro dessa pasta, digite na janela do terminal `code test/test_hello.py`. Observe que `test/` instrui o terminal a criar `test_hello.py` na pasta chamada `test`.
- Na janela do editor de texto, modifique o arquivo para incluir o seguinte código:

      from hello import hello


      def test_default():
          assert hello() == "hello, world"


      def test_argument():
          assert hello("David") == "hello, David"

  Observação que estamos criando um teste da mesma forma que fizemos anteriormente.

- O `pytest` não nos permitirá executar testes como uma pasta simplesmente com este arquivo (ou um conjunto inteiro de arquivos) sozinho, sem um arquivo especial `__init__`. Na janela do terminal, crie este arquivo digitando `code test/__init__.py`. Observe o `test/` como antes, assim como os sublinhados duplos em ambos os lados de `init`. Mesmo deixando este arquivo `__init__.py` vazio, o `pytest` é informado de que a pasta inteira contendo `__init__.py` possui testes que podem ser executados.
- Agora, digitando `pytest test` no terminal, você pode executar toda a pasta `test` de código.

Você pode aprender mais na documentação do Pytest sobre [mecanismos de importação](https://docs.pytest.org/en/7.1.x/explanation/pythonpath.html?highlight=folder#pytest-import-mechanisms-and-sys-path-pythonpath).

## Resumindo

Testar o seu código é uma parte natural do processo de programação. Testes unitários permitem testar aspectos específicos do seu código. Você pode criar seus próprios programas que testam seu código. Alternativamente, você pode utilizar frameworks como `pytest` para executar seus testes unitários por você. Nesta palestra, você aprendeu sobre...

- Testes unitários
- `assert`
- `pytest`